import 'dart:io';
import 'package:path/path.dart' as p;
import '../model/annspec_model.dart';

/// Generates lib/generated/scripts/firebase.sh with one `flutterfire configure`
/// command per flavor × platform × buildType, then optionally runs the script.
class FirebaseGenerator {
  static const _buildTypes = ['release', 'debug'];
  static const _platforms  = ['android', 'ios', 'web', 'windows'];

  static void generate(
    AnnspecModel spec,
    String projectRoot, {
    bool runScript = false,
  }) {
    final commands = _buildCommands(spec, projectRoot);

    if (commands.isEmpty) {
      print('  ⚠ No Firebase config found in annspec.yaml — skipping firebase.sh.');
      return;
    }

    final scriptFile = _scriptFile(projectRoot);
    scriptFile.parent.createSync(recursive: true);
    _writeScript(scriptFile, commands);
    print('  ✓ Generated ${p.relative(scriptFile.path, from: projectRoot)}');
    print('    ${commands.length} flutterfire command(s) written.');

    if (runScript) {
      _runScript(scriptFile, projectRoot);
    } else {
      print('    Run it manually:  sh lib/generated/scripts/firebase.sh');
      print('    Or use:           dart run ann_flutter_flavor firebase --run');
    }
  }

  // ── Script runner ──────────────────────────────────────────────────────────

  static void run(String projectRoot) {
    final file = _scriptFile(projectRoot);
    if (!file.existsSync()) {
      print('  ⚠ firebase.sh not found. Run sync first.');
      return;
    }
    _runScript(file, projectRoot);
  }

  // ── Command builder ────────────────────────────────────────────────────────

  static List<_FbCmd> _buildCommands(AnnspecModel spec, String projectRoot) {
    final cmds = <_FbCmd>[];

    for (final platformKey in _platforms) {
      final platform = spec.platform(platformKey);
      if (platform == null) continue;

      for (final flavor in platform.flavors) {
        for (final buildType in _buildTypes) {
          final fb = buildType == 'release'
              ? (flavor.firebaseRelease ?? platform.defaultFirebaseRelease)
              : (flavor.firebaseDebug   ?? platform.defaultFirebaseDebug);

          if (fb?.projectId == null) continue;

          final outFile =
              'lib/generated/firebase/${_fbFile(flavor.key, buildType, platformKey)}';

          final appId = _appId(platform, flavor);

          cmds.add(_FbCmd(
            projectId:   fb!.projectId!,
            outFile:     outFile,
            platform:    platformKey,
            appId:       appId,
            androidOut:  platformKey == 'android' ? fb.path : null,
            iosBuildTarget: platformKey == 'ios' ? fb.buildTarget : null,
            iosOut:      platformKey == 'ios' ? fb.path : null,
            label:       '${flavor.key} / $buildType / $platformKey',
          ));
        }
      }
    }
    return cmds;
  }

  // ── Script writer ──────────────────────────────────────────────────────────

  static void _writeScript(File file, List<_FbCmd> cmds) {
    final buf = StringBuffer();
    buf.writeln('#!/bin/sh');
    buf.writeln('# Generated by ann_flutter_flavor — do not edit manually.');
    buf.writeln('# Run: sh lib/generated/scripts/firebase.sh');
    buf.writeln();
    buf.writeln('set -e');
    buf.writeln('EXIT_CODE=0');
    buf.writeln('ERRORS=""');
    buf.writeln();
    buf.writeln('rm -rf lib/generated/firebase/*');
    buf.writeln();

    for (final cmd in cmds) {
      buf.writeln('# ${cmd.label}');
      buf.write('flutterfire configure -y -f');
      buf.write(' -p ${cmd.projectId}');
      buf.write(' -o "${cmd.outFile}"');
      buf.write(' --platforms=${cmd.platform}');

      if (cmd.appId != null) {
        if (cmd.platform == 'android') buf.write(' -a ${cmd.appId}');
        if (cmd.platform == 'ios')     buf.write(' -i ${cmd.appId}');
      }
      if (cmd.androidOut != null) {
        buf.write(' --android-out="${cmd.androidOut}"');
      }
      if (cmd.iosBuildTarget != null && cmd.iosBuildTarget!.isNotEmpty) {
        buf.write(' --ios-build-config="${cmd.iosBuildTarget}"');
      }
      if (cmd.iosOut != null) {
        buf.write(' --ios-out="${cmd.iosOut}"');
      }
      buf.writeln(r' || { EXIT_CODE=1; ERRORS="${ERRORS}\n  failed: ' '${cmd.label}"; }');
      buf.writeln();
    }

    buf.writeln(r'if [ "$EXIT_CODE" -ne 0 ]; then');
    buf.writeln(r'  echo "\nFirebase sync errors:$ERRORS"');
    buf.writeln(r'  exit "$EXIT_CODE"');
    buf.writeln('fi');
    buf.writeln(r'echo "\n✅  Firebase sync complete."');

    file.writeAsStringSync(buf.toString());
    Process.runSync('chmod', ['+x', file.path]);
  }

  // ── Process runner ─────────────────────────────────────────────────────────

  static void _runScript(File scriptFile, String projectRoot) {
    print('  ▶ Running firebase.sh ...');
    final result = Process.runSync(
      'sh',
      [scriptFile.path],
      workingDirectory: projectRoot,
    );
    stdout.write(result.stdout);
    stderr.write(result.stderr);
    if (result.exitCode != 0) {
      print('  ✗ firebase.sh exited with code ${result.exitCode}');
    } else {
      print('  ✓ Firebase options files generated.');
    }
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  static File _scriptFile(String projectRoot) =>
      File(p.join(projectRoot, 'lib', 'generated', 'scripts', 'firebase.sh'));

  /// Matches dart_generator.dart naming: ledger_in_release_android_firebase_options.dart
  static String _fbFile(String flavor, String buildType, String platform) =>
      '${flavor}_${buildType}_${platform}_firebase_options.dart';

  static String? _appId(AnnspecPlatform platform, AnnspecFlavor flavor) {
    if (platform.baseId == null) return null;
    return flavor.idSuffix != null
        ? '${platform.baseId}${flavor.idSuffix}'
        : platform.baseId;
  }
}

class _FbCmd {
  final String projectId;
  final String outFile;
  final String platform;
  final String? appId;
  final String? androidOut;
  final String? iosBuildTarget;
  final String? iosOut;
  final String label;

  const _FbCmd({
    required this.projectId,
    required this.outFile,
    required this.platform,
    required this.appId,
    required this.androidOut,
    required this.iosBuildTarget,
    required this.iosOut,
    required this.label,
  });
}
