import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:ann_flavor_core/ann_flavor_core.dart' as core;

/// Runs `flutterfire configure` for every flavor × platform × build type
/// that has a project_id in the annspec.yaml, or generates a shell script
/// that the developer can run manually when the environment is ready.
///
/// Auth is via the service_account field only — no ADC or gcloud fallback
/// (REQ-FIRE-00100: no machine-level dependency).
class FirebaseGenerator {
  static const _buildTypes  = ['release', 'debug'];
  static const _platforms   = ['android', 'ios', 'web', 'windows'];
  static const _scriptPath  = 'lib/generated/scripts/firebase.sh';

  // Kill flutterfire if it hasn't finished within this window.
  // Auth prompts or network issues cause it to hang indefinitely otherwise.
  static const _timeout = Duration(seconds: 120);

  static Future<void> generate(
    core.AnnSpec spec,
    String projectRoot, {
    String firebaseMode = 'script',
  }) async {
    // Only run when firebase integration is explicitly enabled.
    if (spec.app.integrations?.firebase != true) {
      print('  ⚠ integrations.firebase is not enabled — skipping flutterfire.');
      return;
    }

    final cmds = _buildCommands(spec);

    if (cmds.isEmpty) {
      print('  ⚠ No Firebase project_id found in annspec.yaml — skipping flutterfire.');
      return;
    }

    if (firebaseMode != 'inline') {
      _writeScript(cmds, projectRoot);
      _patchFirebaseJson(cmds, projectRoot);
      return;
    }

    print('  Running flutterfire configure for ${cmds.length} combination(s)...');
    var failed = 0;

    for (final cmd in cmds) {
      print('  ▶ ${cmd.label}');
      final ok = await _runFlutterfire(cmd, projectRoot);
      if (ok) {
        print('  ✓ Done: ${cmd.label}');
      } else {
        print('  ✗ Failed: ${cmd.label}');
        failed++;
      }
    }

    if (failed > 0) {
      print('  ⚠ $failed flutterfire command(s) failed.');
    } else {
      print('  ✓ Firebase options files generated.');
    }

    _patchFirebaseJson(cmds, projectRoot);
  }

  // ── firebase.json correction ─────────────────────────────────────────────────

  // flutterfire_cli writes its own ios.buildConfigurations.<Config>-<flavor>.fileOutput
  // entries as a side effect of `flutterfire configure`, independent of the
  // --ios-out flag above (which only governs ios.default/ios.targets.*). That
  // value has been observed to end up stale or malformed (e.g. left over from
  // an earlier interactive run with a different --ios-out) and is never
  // corrected by a later flutterfire configure re-run for the same
  // build-configuration key. Since this repo's own build phases already copy
  // each plist to the stable lib/generated/firebase/ path (REQ-FIRE-00148),
  // realign any existing buildConfigurations entry to that same path here —
  // once per sync, deterministically, rather than relying on flutterfire_cli's
  // own merge behavior for that key.
  //
  // Only pre-existing keys are corrected — this never invents a new
  // buildConfigurations entry (that remains flutterfire configure's job).
  static void _patchFirebaseJson(List<_FbCmd> cmds, String projectRoot) {
    final iosCmds = cmds.where((c) => c.platform == 'ios');
    if (iosCmds.isEmpty) return;

    final jsonFile = File(p.join(projectRoot, 'firebase.json'));
    if (!jsonFile.existsSync()) return;

    Map<String, dynamic> root;
    try {
      root = jsonDecode(jsonFile.readAsStringSync()) as Map<String, dynamic>;
    } catch (_) {
      // Malformed firebase.json — leave it alone rather than risk corrupting it further.
      return;
    }

    final buildConfigs = root['flutter']?['platforms']?['ios']?['buildConfigurations'];
    if (buildConfigs is! Map<String, dynamic>) return;

    var changed = false;
    for (final cmd in iosCmds) {
      final configKey = '${_capitalize(cmd.buildType)}-${cmd.flavor}';
      final entry = buildConfigs[configKey];
      if (entry is! Map<String, dynamic>) continue;

      final stablePath = _iosStablePath(cmd.flavor, cmd.buildType);
      if (entry['fileOutput'] != stablePath) {
        entry['fileOutput'] = stablePath;
        changed = true;
      }
    }

    if (changed) {
      jsonFile.writeAsStringSync(jsonEncode(root));
      print('  ✓ firebase.json buildConfigurations realigned to lib/generated/firebase/');
    }
  }

  static String _capitalize(String s) => s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);

  // ── Script generation ────────────────────────────────────────────────────────

  static void _writeScript(List<_FbCmd> cmds, String projectRoot) {
    final scriptFile = File(p.join(projectRoot, _scriptPath));
    scriptFile.parent.createSync(recursive: true);

    final buf = StringBuffer();
    buf.writeln('#!/usr/bin/env bash');
    buf.writeln('# Generated by: dart run ann_flutter_flavor sync --firebase-mode script');
    buf.writeln('# Re-run sync to regenerate. Do not edit manually.');
    buf.writeln();
    buf.writeln('export CI=true    # suppress flutterfire spinners and ANSI escape codes');
    buf.writeln('export TERM=dumb  # force dumb terminal so mason_logger skips spinner even in IDE TTY');
    buf.writeln();
    buf.writeln('SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"');
    buf.writeln('cd "\$SCRIPT_DIR/../../.."  '
        '# lib/generated/scripts → lib/generated → lib → project root');
    buf.writeln();
    buf.writeln('EXIT_CODE=0');
    buf.writeln('ERROR_MESSAGES=""');
    buf.writeln();

    // Remove stale Dart options files before re-running; leave committed JSON/plist in place.
    buf.writeln('rm -f lib/generated/firebase/*_firebase_options.dart');
    buf.writeln('if [ \$? -ne 0 ]; then');
    buf.writeln('  echo "Error: Failed to remove old generated Firebase files."');
    buf.writeln('  EXIT_CODE=1');
    buf.writeln('  ERROR_MESSAGES="\$ERROR_MESSAGES\\n- Failed to remove old generated Firebase files."');
    buf.writeln('fi');
    buf.writeln();

    for (final cmd in cmds) {
      buf.writeln('echo "Configuring ${cmd.label}..."');
      buf.write('flutterfire configure -y -f');
      buf.write(' \\\n  -p ${cmd.projectId}');
      buf.write(' \\\n  -o ${cmd.outFile}');
      buf.write(' \\\n  --platforms=${cmd.platform}');
      if (cmd.platform == 'android') {
        buf.write(' \\\n  --android-out $_androidTempPath');
      } else if (cmd.platform == 'ios') {
        buf.write(' \\\n  --ios-target ${cmd.iosTarget}');
        buf.write(' \\\n  --ios-out $_iosRunnerPath');
      }
      if (cmd.bundleId != null) {
        final flag = cmd.platform == 'ios' ? '-i' : '-a';
        buf.write(' \\\n  $flag ${cmd.bundleId}');
      }
      if (cmd.serviceAccount != null) {
        buf.write(' \\\n  --service-account ${cmd.serviceAccount}');
      }
      buf.writeln();
      buf.writeln('if [ \$? -ne 0 ]; then');
      buf.writeln('  echo "  -> Failed."');
      buf.writeln('  EXIT_CODE=1');
      buf.writeln('  ERROR_MESSAGES="\$ERROR_MESSAGES\\n- ${cmd.label} failed."');
      buf.writeln('else');
      buf.writeln('  echo "  -> Succeeded."');
      if (cmd.platform == 'android') {
        final tmp    = _androidTempPath;
        final stable = _androidStablePath(cmd.flavor, cmd.buildType);
        buf.writeln('  mkdir -p lib/generated/firebase');
        buf.writeln('  mv $tmp $stable');
      } else if (cmd.platform == 'ios') {
        final stable = _iosStablePath(cmd.flavor, cmd.buildType);
        buf.writeln('  mkdir -p lib/generated/firebase');
        buf.writeln('  cp $_iosRunnerPath $stable');
        buf.writeln('  rm $_iosRunnerPath');
      }
      buf.writeln('fi');
      buf.writeln();
    }

    buf.writeln('echo ""');
    buf.writeln('echo "--- Script Execution Summary ---"');
    buf.writeln('if [ "\$EXIT_CODE" -eq 0 ]; then');
    buf.writeln('  echo "All Firebase configurations completed successfully."');
    buf.writeln('else');
    buf.writeln('  echo "Some Firebase configurations failed."');
    buf.writeln('  printf "\$ERROR_MESSAGES\\n"');
    buf.writeln('  echo "--------------------------------"');
    buf.writeln('fi');
    buf.writeln('exit "\$EXIT_CODE"');

    scriptFile.writeAsStringSync(buf.toString());

    // Make executable on POSIX systems.
    if (!Platform.isWindows) {
      Process.runSync('chmod', ['+x', scriptFile.path]);
    }

    print('  ✓ Firebase script generated: $_scriptPath');
    print('    Run it when your Firebase auth is ready:');
    print('      bash $_scriptPath');
  }

  static Future<bool> _runFlutterfire(_FbCmd cmd, String projectRoot) async {
    ProcessResult result;
    try {
      result = await Process.run(
        'flutterfire',
        _buildArgs(cmd),
        workingDirectory: projectRoot,
      ).timeout(_timeout, onTimeout: () {
        print('  ✗ Timed out after ${_timeout.inSeconds}s: ${cmd.label}');
        return ProcessResult(-1, 1, '', '');
      });
    } on ProcessException catch (e) {
      print('  ✗ Could not run flutterfire: ${e.message}');
      print('     Install it with: dart pub global activate flutterfire_cli');
      return false;
    }

    if (result.exitCode == 0) {
      if (cmd.platform == 'android') {
        final tmp    = p.join(projectRoot, _androidTempPath);
        final stable = p.join(projectRoot, _androidStablePath(cmd.flavor, cmd.buildType));
        Directory(p.dirname(stable)).createSync(recursive: true);
        File(tmp).renameSync(stable);
      } else if (cmd.platform == 'ios') {
        final src    = File(p.join(projectRoot, _iosRunnerPath));
        final stable = p.join(projectRoot, _iosStablePath(cmd.flavor, cmd.buildType));
        Directory(p.dirname(stable)).createSync(recursive: true);
        src.copySync(stable);
        src.deleteSync();
      }
      return true;
    }

    final errText = result.stderr.toString();
    if (_isAuthError(errText)) {
      // No machine-auth fallback (REQ-FIRE-00100). Point developer to service_account.
      print('  ✗ Firebase authentication failed for: ${cmd.label}');
      print('     Check the service_account field in your annspec.yaml.');
      print('     The account needs the "Firebase Admin SDK Administrator Service Agent" IAM role.');
    } else {
      stderr.write(errText);
    }
    return false;
  }

  static bool _isAuthError(String text) {
    final lower = text.toLowerCase();
    return lower.contains('unauthenticated') ||
        lower.contains('invalid_grant') ||
        lower.contains('token') && (lower.contains('expired') || lower.contains('revoked')) ||
        lower.contains('authentication required') ||
        lower.contains('not logged in') ||
        lower.contains('please sign in') ||
        lower.contains('failed to get project') ||
        lower.contains('permission denied');
  }

  // ── Stable output paths ──────────────────────────────────────────────────────

  // flutterfire validates --android-out must be named exactly google-services.json
  // under the android/ tree. Use the standard app-level path, then mv to the
  // stable committed location immediately after each command succeeds.
  static const _androidTempPath = 'android/app/google-services.json';

  static String _androidStablePath(String flavor, String buildType) =>
      'lib/generated/firebase/google-services-$flavor-$buildType.json';

  // flutterfire v1.4.0 only accepts --ios-out when basename is exactly GoogleService-Info.plist
  static const _iosRunnerPath = 'ios/Runner/GoogleService-Info.plist';

  static String _iosStablePath(String flavor, String buildType) =>
      'lib/generated/firebase/GoogleService-Info-$flavor-$buildType.plist';

  // ── Command builder ──────────────────────────────────────────────────────────

  static List<_FbCmd> _buildCommands(core.AnnSpec spec) {
    final cmds = <_FbCmd>[];
    final resolved = core.AnnSpecResolver.resolveAll(spec, buildTypes: _buildTypes);

    for (final platformKey in _platforms) {
      final resolvedFlavors = switch (platformKey) {
        'android' => resolved.android,
        'ios'     => resolved.ios,
        'web'     => resolved.web,
        'windows' => resolved.windows,
        _         => const <String, core.ResolvedFlavor>{},
      };
      if (resolvedFlavors.isEmpty) continue;

      final iosPlatform = platformKey == 'ios' ? spec.app.ios : null;

      for (final entry in resolvedFlavors.entries) {
        final flavorKey = entry.key;
        for (final buildType in _buildTypes) {
          final output = entry.value.byBuildType[buildType];
          if (output == null) continue;

          final fb = output.effectiveFirebase;
          if (fb == null) continue;

          // iOS does not use config_file — it downloads config via project_id.
          if (platformKey == 'ios' && fb.configFile != null && fb.projectId == null) {
            throw StateError(
              '[$flavorKey/$buildType/ios] config_file is Android-only.\n'
              '  iOS downloads its config via project_id at build time.\n'
              '  Fix: replace  config_file: "..."  with  project_id: "your-firebase-project-id"\n'
              "  Run 'dart run ann_flutter_flavor validate' for a full spec check.",
            );
          }

          if (fb.projectId == null) continue;

          final outFile =
              'lib/generated/firebase/${flavorKey}_${buildType}_${platformKey}_firebase_options.dart';

          // Fully resolved bundle ID — includes the build-type suffix, unlike
          // the old mirror-based computation which silently dropped it.
          final bundleId = output.effectiveId;

          final iosTarget = platformKey == 'ios' && iosPlatform != null
              ? core.IosResolution.target(iosPlatform, flavorKey, buildType)
              : null;

          cmds.add(_FbCmd(
            projectId:      fb.projectId!,
            serviceAccount: fb.serviceAccount,
            outFile:        outFile,
            platform:       platformKey,
            label:          '$flavorKey / $buildType / $platformKey',
            flavor:         flavorKey,
            buildType:      buildType,
            bundleId:       bundleId.isEmpty ? null : bundleId,
            iosTarget:      iosTarget,
          ));
        }
      }
    }
    return cmds;
  }

  static List<String> _buildArgs(_FbCmd cmd) {
    final args = [
      'configure', '-y', '-f',
      '-p', cmd.projectId,
      '-o', cmd.outFile,
      '--platforms=${cmd.platform}',
    ];
    if (cmd.platform == 'android') {
      args.addAll(['--android-out', _androidTempPath]);
    } else if (cmd.platform == 'ios') {
      args.addAll(['--ios-target', cmd.iosTarget!]);
      args.addAll(['--ios-out', _iosRunnerPath]);
    }
    if (cmd.bundleId != null) {
      args.addAll([cmd.platform == 'ios' ? '-i' : '-a', cmd.bundleId!]);
    }
    // Service account is the only supported auth method (REQ-FIRE-00100 — no ADC/gcloud fallback).
    if (cmd.serviceAccount != null) {
      args.addAll(['--service-account', cmd.serviceAccount!]);
    }
    return args;
  }
}

class _FbCmd {
  final String projectId;
  final String? serviceAccount;
  final String outFile;
  final String platform;
  final String label;
  final String flavor;
  final String buildType;
  final String? bundleId;        // -i (iOS) or -a (Android)
  final String? iosTarget;  // --target (iOS only, default Runner)

  const _FbCmd({
    required this.projectId,
    this.serviceAccount,
    required this.outFile,
    required this.platform,
    required this.label,
    required this.flavor,
    required this.buildType,
    this.bundleId,
    this.iosTarget,
  });
}
