import 'dart:io';
import 'package:path/path.dart' as p;
import '../model/annspec_model.dart';

class MelosGenerator {
  static const _startMarker =
      '    # ── Generated by ann_flutter_flavor — do not edit this section ──';
  static const _endMarker = '    # ── End ann_flutter_flavor generated section ──';

  static void generate(String projectRoot, AnnspecModel spec) {
    final file = File(p.join(projectRoot, 'pubspec.yaml'));
    if (!file.existsSync()) {
      print('  ⚠️  pubspec.yaml not found — skipping melos script generation');
      return;
    }

    final content = file.readAsStringSync();
    final generated = _buildGeneratedBlock(spec);

    if (content.contains(_startMarker)) {
      final updated = _replaceBlock(content, generated);
      file.writeAsStringSync(updated);
      print('  ✅ melos scripts in pubspec.yaml regenerated');
    } else {
      final updated = _appendBlock(content, generated);
      file.writeAsStringSync(updated);
      print('  ✅ melos scripts added to pubspec.yaml');
    }
  }

  // ── Block generation ─────────────────────────────────────────────────────────

  static String _buildGeneratedBlock(AnnspecModel spec) {
    final buf = StringBuffer();
    buf.writeln(_startMarker);
    buf.writeln('    # Re-run `dart run ann_flutter_flavor sync` to regenerate');

    final platforms = spec.platforms.map((p) => p.key).toSet();

    if (platforms.contains('android')) _appendAndroid(buf);
    if (platforms.contains('ios'))     _appendIos(buf);
    if (platforms.contains('web'))     _appendWeb(buf);
    if (platforms.contains('windows')) _appendWindows(buf);

    _appendCombined(buf, platforms);

    buf.write(_endMarker);
    return buf.toString();
  }

  static void _appendAndroid(StringBuffer buf) {
    buf.writeln('''
    android:build:
      run: fastlane android build {"\$@"}
      description: |
        Build Android APK. Key params: flavor, build_type, clean
    android:build:bundle:
      run: fastlane android build_bundle {"\$@"}
      description: |
        Build Android App Bundle (AAB). Key params: flavor, build_type, clean
    android:upload:
      run: fastlane android upload {"\$@"}
      description: |
        Upload Android build to store. Key params: flavor, track, skip_upload_images, skip_upload_metadata, skip_upload_binary
    android:download:
      run: fastlane android download {"\$@"}
      description: |
        Download Android metadata/screenshots. Key params: flavor, track
    android:test:
      run: fastlane android run_tests {"\$@"}
      description: |
        Run Android tests. Key params: flavor, build_type
    android:emulator:open:
      run: fastlane android open_emulator {"\$@"}
      description: |
        Start Android emulator. Key params: flavor
    android:emulator:close:
      run: fastlane android close_emulator {"\$@"}
      description: |
        Stop Android emulator. Key params: flavor''');
  }

  static void _appendIos(StringBuffer buf) {
    buf.writeln('''
    ios:build:
      run: fastlane ios build {"\$@"}
      description: |
        Build iOS IPA. Key params: flavor, build_type, clean
    ios:upload:
      run: fastlane ios upload {"\$@"}
      description: |
        Upload iOS build to App Store Connect. Key params: flavor, skip_upload_screenshots, skip_upload_metadata, skip_upload_binary
    ios:download:
      run: fastlane ios download {"\$@"}
      description: |
        Download iOS metadata/screenshots. Key params: flavor
    ios:test:
      run: fastlane ios run_tests {"\$@"}
      description: |
        Run iOS tests. Key params: flavor, build_type
    ios:simulator:open:
      run: fastlane ios open_simulator {"\$@"}
      description: |
        Start iOS simulator. Key params: flavor
    ios:simulator:close:
      run: fastlane ios close_simulator {"\$@"}
      description: |
        Stop iOS simulator. Key params: flavor''');
  }

  static void _appendWeb(StringBuffer buf) {
    buf.writeln('''
    web:build:
      run: fastlane web build {"\$@"}
      description: |
        Build web app. Key params: flavor, build_type
    web:upload:
      run: fastlane web upload {"\$@"}
      description: |
        Deploy web app. Key params: flavor''');
  }

  static void _appendWindows(StringBuffer buf) {
    buf.writeln('''
    windows:build:
      run: fastlane windows build {"\$@"}
      description: |
        Build Windows app. Key params: flavor, build_type
    windows:upload:
      run: fastlane windows upload {"\$@"}
      description: |
        Upload Windows app. Key params: flavor''');
  }

  static void _appendCombined(StringBuffer buf, Set<String> platforms) {
    final uploadTargets = <String>[];
    final downloadTargets = <String>[];
    final testTargets = <String>[];

    if (platforms.contains('ios'))     uploadTargets.add('melos run ios:upload');
    if (platforms.contains('android')) uploadTargets.add('melos run android:upload');
    if (platforms.contains('web'))     uploadTargets.add('melos run web:upload');
    if (platforms.contains('windows')) uploadTargets.add('melos run windows:upload');

    if (platforms.contains('ios'))     downloadTargets.add('melos run ios:download');
    if (platforms.contains('android')) downloadTargets.add('melos run android:download');

    if (platforms.contains('ios'))     testTargets.add('melos run ios:test');
    if (platforms.contains('android')) testTargets.add('melos run android:test');

    if (uploadTargets.length > 1) {
      buf.writeln('''
    upload:all:
      run: ${uploadTargets.join(' && ')}
      description: Upload all platforms to their stores''');
    }
    if (downloadTargets.length > 1) {
      buf.writeln('''
    download:all:
      run: ${downloadTargets.join(' && ')}
      description: Download metadata for all platforms''');
    }
    if (testTargets.length > 1) {
      buf.writeln('''
    test:all:
      run: ${testTargets.join(' && ')}
      description: Run tests on all platforms''');
    }

    if (platforms.contains('android') && platforms.contains('ios')) {
      buf.writeln('''
    emulators:open:
      run: melos run android:emulator:open && melos run ios:simulator:open
      description: Start Android emulator and iOS simulator
    emulators:close:
      run: melos run android:emulator:close && melos run ios:simulator:close
      description: Stop Android emulator and iOS simulator''');
    }
  }

  // ── Block splice helpers ──────────────────────────────────────────────────────

  static String _replaceBlock(String content, String generated) {
    final start = content.indexOf(_startMarker);
    final end = content.indexOf(_endMarker);
    if (start == -1 || end == -1) return _appendBlock(content, generated);
    final endOfBlock = end + _endMarker.length;
    return content.substring(0, start) +
        generated +
        content.substring(endOfBlock);
  }

  static String _appendBlock(String content, String generated) {
    if (content.contains('  scripts:')) {
      // Append inside existing scripts: block
      return content.trimRight() + '\n' + generated + '\n';
    }
    // No scripts: block at all — append after melos: key or at end
    if (content.contains('\nmelos:')) {
      return content.trimRight() + '\n  scripts:\n' + generated + '\n';
    }
    return content.trimRight() +
        '\n\nmelos:\n  scripts:\n' +
        generated +
        '\n';
  }
}
